[Metadata]
Author=yonguelink

@include1=#@#Style.inc

; ----------------------------------
; MEASURES return some kind of value
; ----------------------------------

[measureGPU]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=Value8

[measureGPUTemp]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=Value7

; ----------------------------------
; METERS display images, text, bars, etc.
; ----------------------------------

[meterLabelGPU]
Meter=String
MeterStyle=styleTitle
Text=GPU

[meterGPUTemp]
Meter=String
MeterStyle=styleValue
MeasureName=measureGPUTemp
NumOfDecimals=0
Text=%1
Y=7

[meterValueGPU]
Meter=String
MeterStyle=styleValue
MeasureName=measureGPU
Y=28
Text=%1
