[Metadata]
Author=yonguelink

@include1=#@#Style.inc

; ----------------------------------
; MEASURES return some kind of value
; ----------------------------------

[measureCPU]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=Value1

[measureCPUTemp]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=Value2

; ----------------------------------
; METERS display images, text, bars, etc.
; ----------------------------------
[meterLabelCPU]
Meter=String
MeterStyle=styleTitle
Text=CPU

[meterCPUTemp]
Meter=String
MeterStyle=styleValue
MeasureName=measureCPUTemp
Text=%1
Y=7

[meterValueCPU]
Meter=String
MeterStyle=styleValue
MeasureName=measureCPU
Text=%1
Y=28
