; This file contains all variables that you should change
[Variables]
;------------
; Screen Position To Sample Colors
;------------
PosX=1760
PosY=484
LumWidth=160
LumHeight=(4 * 38) + (4 * 18) + (8 * 5)

; Doc: https://docs.rainmeter.net/tips/hwinfo/
; RAM% Index = 0
; CPU% Index = 1
; CPU Temp Index = 2
; Water Temp Index = 3

; Top Fan : CPU Index= 4
; Middle Fan: HWPUMP Index= 5
; Bottom Fan: Sys 4 Index= 6

; GPU Temp Index = 7
; GPU% Index = 8
