; This file contains all variables that you should change
[Variables]
; -----------
; CPU
; -----------

HWiNFO-CPU0-DTS-SensorId=0xf0000400
HWiNFO-CPU0-DTS-SensorInstance=0x0
HWiNFO-CPU0-DTS-Core0temp=0x1000000
HWiNFO-CPU-Usage-SensorId=0xf0000300
HWiNFO-CPU-Usage-SensorInstance=0x0
HWiNFO-CPU-Usage-EntryId=0x700000d

; -----------
; RAM
; -----------

RAM-SensorId=0xf0000301
RAM-SensorInstance=0x0
RAM-EntryId=0x8000005

; -----------
; GPU
; -----------

GPU-TEMP-SensorId=0xe0002000
GPU-TEMP-SensorInstance=0x0
GPU-TEMP-EntryId=0x1000000

GPU-USAGE-SensorId=0xe0002000
GPU-USAGE-SensorInstance=0x0
GPU-USAGE-EntryId=0x7000000


; -----------
; Water Cooling
; -----------

WATER-TEMP-SensorId=0xf0008686
WATER-TEMP-SensorInstance=0x0
WATER-TEMP-EntryId=0x1000005

PUMP-SPEED-SensorId=0xf0008686
PUMP-SPEED-SensorInstance=0x0
PUMP-SPEED-EntryId=0x3000000

FAN1-SPEED-SensorId=0xf0008686
FAN1-SPEED-SensorInstance=0x0
FAN1-SPEED-EntryId=0x3000001

FAN2-SPEED-SensorId=0xf0008686
FAN2-SPEED-SensorInstance=0x0
FAN2-SPEED-EntryId=0x3000003

FAN3-SPEED-SensorId=0xf0008733
FAN3-SPEED-SensorInstance=0x1
FAN3-SPEED-EntryId=0x3000002
