;MEASURES
[Rainmeter]
Update=1000

[MeasureHour]
Measure=Time
Format=%H

[MeasureMinute]
Measure=Time
Format=%M

[MeasureSecond]
Measure=Time
Format=%S


;METERS

[MeterHour]
MeasureName=MeasureHour
Meter=String
MeterStyle=styleTitle
X=0
Y=0
FontSize=48
FontColor=c1c1c1
FontFace=Silverball
InlineSetting=Shadow | 0 | 0 | 0.01 | #1e1e1e


[DoubleDotsHourMinute]
Meter=String
X=80
Y=10
Text=":"
FontSize=30
FontColor=c1c1c1
FontFace=Calibri
InlineSetting=Shadow | 0 | 0 | 0.01 | #1e1e1e

[MeterMinute]
MeasureName=MeasureMinute
Meter=String
MeterStyle=styleTitle
X=90
Y=0
FontSize=48
FontColor=c1c1c1
FontFace=Silverball
InlineSetting=Shadow | 0 | 0 | 0.01 | #1e1e1e

[DoubleDotsMinuteSecond]
Meter=String
X=165
Y=10
Text=":"
FontSize=30
FontColor=c1c1c1
FontFace=Calibri
InlineSetting=Shadow | 0 | 0 | 0.01 | #1e1e1e

[MeterSecond]
MeasureName=MeasureSecond
Meter=String
MeterStyle=styleTitle
X=175
Y=0
FontSize=48
FontColor=c1c1c1
FontFace=Silverball
InlineSetting=Shadow | 0 | 0 | 0.01 | #1e1e1e

[TimeMinutesTest]
Measure=Time
Format=%S
; UpdateDivider=60 means this measure only updates every 60 skin updates.
; With Update=1000, the skin updates every second, so after 60 seconds, this measure updates once.
IfCondition=(#CURRENTSECTION# % 2)=0
IfTrueAction=[!ShowMeter "DoubleDotsHourMinute"][!ShowMeter "DoubleDotsMinuteSecond"]
IfFalseAction=[!HideMeter "DoubleDotsHourMinute"][!HideMeter "DoubleDotsMinuteSecond"]