[Metadata]
Author=yonguelink

@include1=#@#Style.inc

; ----------------------------------
; MEASURES return some kind of value
; ----------------------------------

[measureWaterTempRegistry]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=Value3

; [measurePumpSpeed]
; Measure=Plugin
; Plugin=HWiNFO.dll
; HWiNFOSensorId=#PUMP-SPEED-SensorId#
; HWiNFOSensorInstance=#PUMP-SPEED-SensorInstance#
; HWiNFOEntryId=#PUMP-SPEED-EntryId#
; HWiNFOType=CurrentValue
; DynamicVariables=1

[measureTopFanSpeed]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=Value4

[measureMiddleFanSpeed]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=Value5

[measureBottomFanSpeed]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=Value6

; ----------------------------------
; METERS display images, text, bars, etc.
; ----------------------------------

[meterLabelWater]
Meter=String
MeterStyle=styleSmallTitle
Text=WATER

[meterWaterTemp]
Meter=String
MeterStyle=styleValue
MeasureName=measureWaterTempRegistry
NumOfDecimals=0
Y=0
Text=%1


; TOP FAN
[meterFan1SpeedLabel]
Meter=String
MeterStyle=styleSmallTitle
Y=25
Text=TOP

[meterTopFanSpeed]
Meter=String
MeterStyle=styleValue
MeasureName=measureTopFanSpeed
NumOfDecimals=0
Y=25
Text=%1

; MIDDLE FAN
[meterMiddleFanSpeedLabel]
Meter=String
MeterStyle=styleSmallTitle
Y=50
Text=MIDDLE

[meterMiddleFanSpeed]
Meter=String
MeterStyle=styleValue
MeasureName=measureMiddleFanSpeed
NumOfDecimals=0
Y=50
Text=%1

; BOTTOM FAN
[meterBottomFanSpeedLabel]
Meter=String
MeterStyle=styleSmallTitle
Y=75
Text=BOTTOM

[meterBottomFanSpeed]
Meter=String
MeterStyle=styleValue
MeasureName=measureBottomFanSpeed
NumOfDecimals=0
Y=75
Text=%1

; PUMP
; [meterPumpSpeedLabel]
; Meter=String
; MeterStyle=styleSmallTitle
; Y=100
; Text=PUMP

; [meterPumpSpeed]
; Meter=String
; MeterStyle=styleValue
; MeasureName=measurePumpSpeed
; NumOfDecimals=0
; Y=100
; Text=%1 RPM
